services:
  docs:
    image: ghcr.io/typo3-documentation/render-guides
    entrypoint: ['/opt/guides/entrypoint.sh', '--config', 'Documentation', '--output', '/result']
    pull_policy: always
    volumes:
      - .:/project:ro
      - .build/docs:/result
