#!/usr/bin/env bash
set -e

## Description: Run npm command to build assets
## Usage: assets [command] [options]
## Example: ddev assets install\nddev assets start\nddev assets run build\nddev assets run check\nddev assets run fix

npm --prefix /var/www/html/Build/assets "$@"
