name: Frontend assets
on:
  pull_request:
    paths:
      - 'Resources/Private/Frontend/**'

jobs:
  rebuild:
    if: ${{ github.actor == 'renovate[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REBUILD_ASSETS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'Resources/Private/Frontend/package-lock.json'

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        run: npm --prefix Resources/Private/Frontend ci

      # Re-create Frontend dist files
      - name: Re-create dist files
        run: npm --prefix Resources/Private/Frontend run build

      # Update PR
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[TASK] Automatically rebuild frontend assets'
          commit_author: 'Elias Häußler <elias@haeussler.dev>'
