name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1

  asset-integrity:
    name: 'Verify asset integrity'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    secrets:
      ASSETS_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/asset-integrity.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1
    with:
      base-path: Build/assets

  checks:
    name: 'Checks'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore
      npm: true
      assets-path: Build/assets

  tests:
    name: 'Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        typo3-version: ["13.4", "14.3"]
        dependencies: ["highest", "lowest"]

    uses: eliashaeussler/gha/.github/workflows/typo3-tests.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1
    with:
      php-version: ${{ matrix.php-version }}
      typo3-version: ${{ matrix.typo3-version }}
      dependencies: ${{ matrix.dependencies }}

  test-coverage:
    name: 'Test coverage'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    uses: eliashaeussler/gha/.github/workflows/typo3-test-coverage.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1
