name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0

  asset-integrity:
    name: 'Verify asset integrity'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    secrets:
      ASSETS_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/asset-integrity.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
    with:
      base-path: Build/assets

  checks:
    name: 'Checks'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    permissions:
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore
      npm: true
      assets-path: Build/assets

  tests:
    name: 'Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        typo3-version: ["13.4", "14.3"]
        dependencies: ["highest", "lowest"]

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
    with:
      php-version: ${{ matrix.php-version }}
      typo3-version: ${{ matrix.typo3-version }}
      dependencies: ${{ matrix.dependencies }}
      boot-mysql: true

  test-coverage:
    name: 'Test coverage'

    needs: [asset-integrity]
    if: ${{ needs.asset-integrity.outputs.rebuilt == 'false' }}

    uses: eliashaeussler/gha/.github/workflows/composer-test-coverage.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
    with:
      coverage-file: Build/tests/coverage/clover.xml
      boot-mysql: true
