name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@main

  assets:
    name: Verify asset integrity
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    outputs:
      modified: ${{ steps.commit.outputs.changes_detected || 'false' }}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.REBUILD_ASSETS_TOKEN }}
          fetch-depth: 0

      # Preconditions
      - name: Check modified assets
        id: check
        run: |
          if git diff --name-only ${{ github.sha }}~1 ${{ github.sha }} | grep -q '^Resources/Private/Frontend/'; then
            echo "skip_assets=false" >> $GITHUB_OUTPUT
          else
            echo "skip_assets=true" >> $GITHUB_OUTPUT
          fi

      # Prepare environment
      - name: Setup Node
        uses: actions/setup-node@v5
        if: ${{ steps.check.outputs.skip_assets != 'true' }}
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'Resources/Private/Frontend/package-lock.json'

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        if: ${{ steps.check.outputs.skip_assets != 'true' }}
        run: npm --prefix Resources/Private/Frontend ci

      # Re-create Frontend dist files
      - name: Re-create dist files
        if: ${{ steps.check.outputs.skip_assets != 'true' }}
        run: npm --prefix Resources/Private/Frontend run build

      - name: Fail on integrity mismatch
        if: ${{ github.actor != 'renovate[bot]' && steps.check.outputs.skip_assets != 'true' }}
        run: |
          git add Resources/Public
          git diff --exit-code --staged Resources/Public

      # Update PR
      - uses: stefanzweifel/git-auto-commit-action@v6
        if: ${{ github.actor == 'renovate[bot]' && steps.check.outputs.skip_assets != 'true' }}
        id: commit
        with:
          commit_message: '[TASK] Automatically rebuild frontend assets'
          commit_author: 'Elias Häußler <elias@haeussler.dev>'
          commit_user_name: 'Elias Häußler'
          commit_user_email: 'elias@haeussler.dev'

  cgl:
    name: CGL
    runs-on: ubuntu-latest
    if: ${{ needs.assets.outputs.modified == 'false' }}
    needs: assets
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2, cs2pr
          coverage: none
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'Resources/Private/Frontend/package-lock.json'

      # Validation
      - name: Validate composer.json
        run: composer validate --strict

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      # Analyze
      - name: Analyze dependencies
        run: composer cgl analyze:dependencies

      # Linting
      - name: Lint composer.json
        run: composer cgl lint:composer
      - name: Lint Editorconfig
        run: composer cgl lint:editorconfig
      - name: Lint PHP
        run: composer cgl lint:php -- --format=checkstyle | cs2pr

      # SCA
      - name: SCA PHP
        run: composer cgl sca:php -- --error-format github

      # Install Frontend dependencies
      - name: Install Frontend dependencies
        run: npm --prefix Resources/Private/Frontend ci

      # Frontend linting
      - name: Lint SCSS
        run: npm --prefix Resources/Private/Frontend run lint:scss
      - name: Lint TypeScript
        run: npm --prefix Resources/Private/Frontend run lint:ts

      # Migration
      - name: Rector migration
        run: composer cgl migration:rector -- --dry-run

      # Documentation
      - name: Check documentation build
        run: |
          mkdir -p .build/docs
          composer docs:build -- --no-progress --fail-on-log

  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    if: ${{ needs.assets.outputs.modified == 'false' }}
    needs: assets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1", "8.2", "8.3", "8.4"]
        typo3-version: ["11.5", "12.4", "13.4"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.1"
            typo3-version: "13.4"
          - php-version: "8.4"
            typo3-version: "11.5"
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run tests
        run: composer test

  test-coverage:
    name: Test coverage
    if: ${{ needs.assets.outputs.modified == 'false' }}
    needs: assets
    runs-on: ubuntu-latest
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: pcov

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      # Run tests
      - name: Run tests
        run: composer test:coverage

      # Upload artifact
      - name: Fix coverage path
        working-directory: .build/coverage
        run: sed -i 's#/home/runner/work/typo3-solver/typo3-solver#${{ github.workspace }}#g' clover.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .build/coverage/clover.xml
          retention-days: 7

  report-coverage:
    name: Report test coverage
    needs: test-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Download artifact
      - name: Download coverage artifact
        id: download
        uses: actions/download-artifact@v5
        with:
          name: coverage

      # CodeClimate
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v9.0.0
        if: env.CC_TEST_REPORTER_ID
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ steps.download.outputs.download-path }}/clover.xml:clover

      # Coveralls
      - name: Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.download.outputs.download-path }}/clover.xml
