name: 'Merge Renovate branch'

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [CI]
    types: [completed]
    branches: ['renovate/*']

permissions:
  contents: read

jobs:
  merge:
    name: 'Merge Renovate branch'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    secrets:
      MERGE_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/merge.yaml@5344de65c90275de4c729d973f1fe7246ea23ee1 # 0.6.3
