name: 'Merge Renovate branch'

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [CI]
    types: [completed]
    branches: ['renovate/*']

permissions:
  contents: read

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    secrets:
      MERGE_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/merge.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
