name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    secrets:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/typo3-extension-release.yaml@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
    with:
      php-version: 8.2 # renovate-ignore
      packaging-excludes-file: Build/release/packaging_exclude.php
