name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    secrets:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/typo3-extension-release.yaml@4d49615252d2d4710ef8ec80f45dc2cfa95071d5 # 0.9.4
    with:
      php-version: 8.2 # renovate-ignore
      packaging-excludes-file: Build/release/packaging_exclude.php
