name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    secrets:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/typo3-extension-release.yaml@8c4f4729925a8ec534dcb4647c154bab6e7594e4 # 1.1.9
    with:
      php-version: 8.2 # renovate-ignore
      packaging-excludes-file: Build/release/packaging_exclude.php
