name: Renovate
on:
  push:
    branches:
      - 'renovate/**'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-exists: ${{ steps.check.outputs.pr-exists }}
    steps:
      - name: Check if PR exists
        id: check
        uses: eliashaeussler/.github/actions/github/check-pr@1.0.0

  trigger-cgl:
    needs: check-pr
    if: '!needs.check-pr.outputs.pr-exists'
    uses: ./.github/workflows/cgl.yaml

  trigger-tests:
    needs: check-pr
    if: '!needs.check-pr.outputs.pr-exists'
    uses: ./.github/workflows/tests.yaml
