name: Renovate update
on:
  push:
    branches:
      - 'renovate/**'
  pull_request:
    branches:
      - 'renovate/**'

jobs:
  renovate-update:
    if: ${{ github.actor == 'renovate[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Install Frontend dependencies
        run: yarn --cwd Resources/Private/Frontend --frozen-lockfile

      # Normalize composer.json
      - name: Normalize composer.json
        run: composer normalize --no-check-lock

      # Re-create Frontend dist files
      - name: Re-create dist files
        run: |
          yarn --cwd Resources/Private/Frontend build
          git add Resources/Public/Css Resources/Public/JavaScript

      # Update PR
      - name: Get last commit message
        id: last-commit-message
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
