name: Tests
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1", "8.2", "8.3"]
        typo3-version: ["11.5", "12.4", "13.1"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.1"
            typo3-version: "13.1"
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run tests
        run: composer test

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: pcov

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test:coverage

      # Upload artifact
      - name: Fix coverage path
        working-directory: .build/coverage
        run: sed -i 's#/home/runner/work/typo3-solver/typo3-solver#${{ github.workspace }}#g' clover.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .build/coverage/clover.xml
          retention-days: 7

  coverage-report:
    name: Report test coverage
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Download artifact
      - name: Download coverage artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: coverage

      # CodeClimate
      - name: CodeClimate report
        uses: paambaati/codeclimate-action@v6.0.0
        if: env.CC_TEST_REPORTER_ID
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ steps.download.outputs.download-path }}/clover.xml:clover

      # Coveralls
      - name: Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.download.outputs.download-path }}/clover.xml
